# Generated by Django 3.2.2 on 2021-05-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(max_length=800, upload_to='contentImages/category', verbose_name='Превью категории')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('editor', models.CharField(blank=True, max_length=200, verbose_name='Редактор')),
                ('tags', models.TextField(blank=True, max_length=1500, verbose_name='Теги')),
                ('sources', models.TextField(blank=True, max_length=500, verbose_name='Источники')),
                ('show', models.BooleanField(default=False, verbose_name='Показывать?')),
                ('published_at', models.DateTimeField(verbose_name='Время публикации')),
                ('category', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='content.category', verbose_name='Категория поста')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='content.type', verbose_name='Тип категории'),
        ),
    ]
