# Generated by Django 3.2.2 on 2021-05-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='name_ru',
            field=models.CharField(default='Проверка', max_length=100, unique=True, verbose_name='Русское название'),
        ),
    ]
