# Generated by Django 3.2.2 on 2021-05-12 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_type_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 10, 40, 34, 996037), verbose_name='Время публикации'),
        ),
    ]
