# Generated by Django 3.2.2 on 2021-05-12 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210512_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=150, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 11, 4, 4, 55897), verbose_name='Время публикации'),
        ),
    ]
