# Generated by Django 3.2.2 on 2021-05-13 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210512_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('content', models.TextField()),
                ('show', models.BooleanField(default=False, verbose_name='Показывать?')),
                ('published_at', models.DateTimeField(default=datetime.datetime(2021, 5, 13, 9, 59, 1, 581243, tzinfo=utc), verbose_name='Время публикации')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 9, 59, 1, 580580, tzinfo=utc), verbose_name='Время публикации'),
        ),
        migrations.CreateModel(
            name='serie_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_links', to='content.post', verbose_name='Пост')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_links', to='content.serie', verbose_name='Серия')),
            ],
        ),
    ]
