# Generated by Django 3.2.2 on 2021-05-13 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210513_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 5, 13, 10, 3, 18, 758729, tzinfo=utc), max_length=800, upload_to='contentImages/series', verbose_name='Превью серии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 10, 2, 57, 205094, tzinfo=utc), verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 10, 2, 57, 205974, tzinfo=utc), verbose_name='Время публикации'),
        ),
    ]
