# Generated by Django 3.2.2 on 2021-05-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210513_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время публикации'),
        ),
    ]
