# Generated by Django 3.2.2 on 2021-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210513_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='posts',
            field=models.ManyToManyField(to='content.Post'),
        ),
    ]
