# Generated by Django 3.2.2 on 2021-05-13 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_serie_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='slug',
            field=models.CharField(default=datetime.datetime(2021, 5, 13, 10, 21, 13, 634291, tzinfo=utc), max_length=100, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
