# Generated by Django 3.2.2 on 2021-05-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_rate_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
