# Generated by Django 3.2.2 on 2021-05-14 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_type_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
    ]
